In [4]:
import numpy as np
def num_arr():
    return np.array(range(6,404,4))
num_arr()

array([  6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,
        58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106,
       110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158,
       162, 166, 170, 174, 178, 182, 186, 190, 194, 198, 202, 206, 210,
       214, 218, 222, 226, 230, 234, 238, 242, 246, 250, 254, 258, 262,
       266, 270, 274, 278, 282, 286, 290, 294, 298, 302, 306, 310, 314,
       318, 322, 326, 330, 334, 338, 342, 346, 350, 354, 358, 362, 366,
       370, 374, 378, 382, 386, 390, 394, 398, 402])

In [5]:
#2
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[~np.isnan(a)]
a

array([1., 2., 3., 5., 6., 7.])

In [6]:
#3
from numpy import random
x = random.randint(100, size = (5,6))
for line in x:
    print(line.max())
x

81
53
84
94
91


array([[ 6,  6, 72, 81, 16, 26],
       [ 0, 22, 34, 24, 32, 53],
       [39,  3, 65, 63, 84, 41],
       [59,  0, 63, 80, 86, 94],
       [51, 16, 53, 81, 49, 91]])

In [8]:
#4
import pandas as pd
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))
pd.unique(series)
series.value_counts()

g    39
p    37
i    37
a    35
f    35
l    33
d    33
o    32
e    32
k    30
m    29
h    28
b    28
c    27
j    25
n    20
dtype: int64

In [18]:
#5
from dateutil.parser import parse
series = pd.Series(['01 Jan 2020', '10-19-2020', '20150303', '2013/04/04', '2012-05-05', '2013-06-06T12:20'])
print("Original Series:")
print(series)
series = series.map(lambda x: parse(x))

print("Day of month:")
print(series.dt.day.tolist())
print("Day of year:")
print(series.dt.dayofyear.tolist())
print("Week number:")
print(series.dt.isocalendar().week.tolist())
print("Day of week:")
print(series.dt.weekday.tolist())

Original Series:
0         01 Jan 2020
1          10-19-2020
2            20150303
3          2013/04/04
4          2012-05-05
5    2013-06-06T12:20
dtype: object
Day of month:
[1, 19, 3, 4, 5, 6]
Day of year:
[1, 293, 62, 94, 126, 157]
Week number:
[1, 43, 10, 14, 18, 23]
Day of week:
[2, 0, 1, 3, 5, 3]


In [19]:
#6
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
len(pd.unique(df.dtypes))
df2 = df.rename(columns={"Type": "TypeOfCar"})
df2.head()
df.isnull().sum()
df.isnull().sum().idxmax()

'Luggage.room'

In [20]:
#7
new_df = df.drop(columns=['Length', 'EngineSize'])
new_df2 = df.drop(['Length', 'EngineSize'], axis=1)
new_df2.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0         31.0                None      Front  ...               13.2   
1         25.0  Driver & Passenger      Front  ...               18.0   
2         26.0         Driver only      Front  ...               16.9   
3         26.0  Driver & Passenger        NaN  ...               21.1   
4         30.0                 NaN       Rear  ...               21.1   

   Passengers  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0         5.0      102.0   68.0        37.0            26.5           NaN   
1         5.0      115.0   71.0        38.0            30.0          15.0   
2         5.0      102.0   67.0        37.0            28.0          14.0   
3         6.0      106.0    NaN        37.0            31.0          17.0   
4         4.0      109.0   69.0        39.0            27.0          13.0   

   Weight   Origin           Make  
0  2705.0  non-USA  Acura Integra  
1  3560.0  non-USA   Acura Legend  
2  3375.0  non-USA        Audi 90  
3  3405.0  non-USA       Audi 100  
4  3640.0  non-USA       BMW 535i  

[5 rows x 25 columns]

In [21]:
#8
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

df1 = df1.drop_duplicates(subset='fruit', keep='first')
df2 = df2.drop_duplicates(subset='pazham', keep='first')

merged_df = df1.merge(df2, left_on='fruit', right_on='pazham')
merged_df

fruit weight  price_x  pazham  kilo  price_y
0   apple   high        9   apple  high        9
1  orange    low        5  orange   low        5

In [22]:
#9
df = pd.DataFrame(["STD,City\tState",
"33,Kolkata\tWest Bengal",
"44,Chennai\tTamil Nadu",
"40,Hyderabad\tTelengana",
"80,Bangalore\tKarnataka"], columns=['row'])
df_out = df.row.str.split(',|\t', expand=True)
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD       City        State
1  33    Kolkata  West Bengal
2  44    Chennai   Tamil Nadu
3  40  Hyderabad    Telengana
4  80  Bangalore    Karnataka


In [27]:
#10
import matplotlib.pyplot as plt
names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin", "car_name"]
df_mpg = pd.read_csv("C:\Users\Shaishta Pandea\Desktop\FTBootCamp\DI_BOOTCAMP\di_exercises\Week7\Day1\auto-mpg.data", header=None, names=names, delim_whitespace=True)
def scatter_plot(df):
    plt.scatter(df['displacement'], df['acceleration'])
    plt.xlabel('displacement')
    plt.ylabel('acceleration')
    plt.grid() 
    plt.show()
scatter_plot(df_mpg)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_15480/1112469145.py, line 4)

In [29]:
#11
def bar_plot_acc(df):
    average_acc_70 = df[df.model_year == 78].acceleration.mean()
    average_acc_82 = df[df.model_year == 82].acceleration.mean()
    index = ['average acceleration 78','average acceleration 82']
    acc = [average_acc_70, average_acc_82]
    df = pd.DataFrame({'acceleration': acc}, index=index)
    ax = df.plot.bar(rot=0)
bar_plot_acc(df_mpg)

NameError: name 'df_mpg' is not defined

In [30]:
def line_plot(df):
    weight = df[df.car_name.str.contains('toyota')].weight
    year = df[df.car_name.str.contains('toyota')].model_year
    plt.plot(year, weight)
    plt.xlabel('model_year')
    plt.ylabel('weight(kg)')
    plt.title('toyota weight throughout the years')
    plt.show()
line_plot(df_mpg)

NameError: name 'df_mpg' is not defined